### ISSUE TITLE
Application Crash while viewing all the roles

### ISSUE THREAD

**Issue by abhi1693** [ShawnClake/UserExtended#14]
![error](https://cloud.githubusercontent.com/assets/5083532/22149592/a395791e-df3a-11e6-90bd-106567574aad.png)

The same error is also thrown while creating roles. But still the roles are created nonetheless.

**Comment by ShawnClake** [comment]
Hi, thanks for the bug report.

I am going to need a little more detail in order to fix this. Can you provide a list of steps to reproduce the problem?

Thanks

**Comment by abhi1693** [comment]
1. I installed the plugin
2. Opened Roles Manager
3. Selected a role
4. Click on Add roles
5. While adding the role for the selected group, I get this error

Still the role is added after the error is thrown.

**Comment by abhi1693** [comment]
```
Stack trace:
#0 /var/www/html/modules/backend/widgets/Lists.php(844): Backend\Widgets\Lists->evalCustomListType('tinytext', Object(Clake\Userextended\Models\Roles), Object(Backend\Classes\ListColumn), 'Full access to ...')
#1 /var/www/html/modules/backend/widgets/lists/partials/_list_body_row.htm(27): Backend\Widgets\Lists->getColumnValue(Object(Clake\Userextended\Models\Roles), Object(Backend\Classes\ListColumn))
#2 /var/www/html/modules/system/traits/ViewMaker.php(244): include('/var/www/html/m...')
#3 /var/www/html/modules/system/traits/ViewMaker.php(98): Backend\Classes\WidgetBase->makeFileContents('/var/www/html/m...', Array)
#4 /var/www/html/modules/backend/widgets/lists/partials/_list_body_rows.htm(2): Backend\Classes\WidgetBase->makePartial('_list_body_row....', Array)
#5 /var/www/html/modules/system/traits/ViewMaker.php(244): include('/var/www/html/m...')
#6 /var/www/html/modules/system/traits/ViewMaker.php(98): Backend\Classes\WidgetBase->makeFileContents('/var/www/html/m...', Array)
#7 /var/www/html/modules/backend/widgets/lists/partials/_list.htm(8): Backend\Classes\WidgetBase->makePartial('_list_body_rows...')
#8 /var/www/html/modules/system/traits/ViewMaker.php(244): include('/var/www/html/m...')
#9 /var/www/html/modules/system/traits/ViewMaker.php(98): Backend\Classes\WidgetBase->makeFileContents('/var/www/html/m...', Array)
#10 /var/www/html/modules/backend/widgets/lists/partials/_list-container.htm(2): Backend\Classes\WidgetBase->makePartial('_list.htm')
#11 /var/www/html/modules/system/traits/ViewMaker.php(244): include('/var/www/html/m...')
#12 /var/www/html/modules/system/traits/ViewMaker.php(98): Backend\Classes\WidgetBase->makeFileContents('/var/www/html/m...', Array)
#13 /var/www/html/modules/backend/widgets/Lists.php(235): Backend\Classes\WidgetBase->makePartial('_list-container...')
#14 /var/www/html/modules/backend/behaviors/listcontroller/partials/_container.htm(9): Backend\Widgets\Lists->render()
#15 /var/www/html/modules/system/traits/ViewMaker.php(244): include('/var/www/html/m...')
#16 /var/www/html/modules/backend/classes/ControllerBehavior.php(142): Backend\Classes\Controller->makeFileContents('/var/www/html/m...', Array)
#17 /var/www/html/modules/system/traits/ViewMaker.php(98): Backend\Classes\ControllerBehavior->makeFileContents('/var/www/html/m...', Array)
#18 /var/www/html/modules/backend/behaviors/ListController.php(371): Backend\Classes\ControllerBehavior->makePartial('_container.htm', Array)
#19 /var/www/html/modules/backend/behaviors/ListController.php(358): Backend\Behaviors\ListController->listMakePartial('container', Array)
#20 [internal function]: Backend\Behaviors\ListController->listRender()
#21 /var/www/html/vendor/october/rain/src/Extension/ExtendableTrait.php(366): call_user_func_array(Array, Array)
#22 /var/www/html/vendor/october/rain/src/Extension/Extendable.php(42): October\Rain\Extension\Extendable->extendableCall('listRender', Array)
#23 /var/www/html/plugins/clake/userextended/controllers/roles/index.htm(2): October\Rain\Extension\Extendable->__call('listRender', Array)
#24 /var/www/html/modules/system/traits/ViewMaker.php(244): include('/var/www/html/p...')
#25 /var/www/html/modules/system/traits/ViewMaker.php(110): Backend\Classes\Controller->makeFileContents('/var/www/html/p...')
#26 /var/www/html/modules/backend/classes/Controller.php(367): Backend\Classes\Controller->makeView('index')
#27 /var/www/html/modules/backend/classes/Controller.php(249): Backend\Classes\Controller->execPageAction('index', Array)
#28 /var/www/html/modules/backend/classes/BackendController.php(106): Backend\Classes\Controller->run('index', Array)
#29 [internal function]: Backend\Classes\BackendController->run('clake/userexten...')
#30 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(256): call_user_func_array(Array, Array)
#31 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(164): Illuminate\Routing\Controller->callAction('run', Array)
#32 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(112): Illuminate\Routing\ControllerDispatcher->call(Object(Backend\Classes\BackendController), Object(Illuminate\Routing\Route), 'run')
#33 [internal function]: Illuminate\Routing\ControllerDispatcher->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#34 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(139): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#35 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#36 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(102): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#37 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(114): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#38 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(67): Illuminate\Routing\ControllerDispatcher->callWithinStack(Object(Backend\Classes\BackendController), Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request), 'run')
#39 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Route.php(203): Illuminate\Routing\ControllerDispatcher->dispatch(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request), 'Backend\\Classes...', 'run')
#40 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Route.php(134): Illuminate\Routing\Route->runWithCustomDispatcher(Object(Illuminate\Http\Request))
#41 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(708): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#42 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#43 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(139): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#44 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#45 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(102): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#46 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(710): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#47 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(673): Illuminate\Routing\Router->runRouteWithinStack(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request))
#48 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(635): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#49 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(236): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#50 [internal function]: Illuminate\Foundation\Http\Kernel->Illuminate\Foundation\Http\{closure}(Object(Illuminate\Http\Request))
#51 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(139): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#52 /var/www/html/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#53 [internal function]: Illuminate\View\Middleware\ShareErrorsFromSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#54 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
#55 /var/www/html/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(62): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#56 [internal function]: Illuminate\Session\Middleware\StartSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#57 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
#58 /var/www/html/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#59 [internal function]: Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse->handle(Object(Illuminate\Http\Request), Object(Closure))
#60 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
#61 /var/www/html/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(59): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#62 [internal function]: Illuminate\Cookie\Middleware\EncryptCookies->handle(Object(Illuminate\Http\Request), Object(Closure))
#63 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
#64 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php(44): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#65 [internal function]: Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode->handle(Object(Illuminate\Http\Request), Object(Closure))
#66 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
#67 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#68 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(102): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#69 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(122): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#70 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(87): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter(Object(Illuminate\Http\Request))
#71 /var/www/html/index.php(43): Illuminate\Foundation\Http\Kernel->handle(Object(Illuminate\Http\Request))
#72 {main}  
```

**Comment by ShawnClake** [comment]
Thank you for the update on this, I'll start looking into it later today.

**Comment by ShawnClake** [comment]
Is this still an issue?

**Comment by abhi1693** [comment]
I haven't tested the plugin in a while.

**Comment by ShawnClake** [comment]
Did a fresh install test with the pre-release code and this doesn't seem to be reproducible anymore. I'm going to mark this as closed. If it reappears, I will reopen the issue.
